version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy_aug07
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik/config:/etc/traefik
    container_name: traefik
    restart: always

  whoami:
    image: "containous/whoami"
    networks:
      - proxy_aug07
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`dashboard.eoas.ubc.ca`) && PathPrefix(`/try1`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.services.whoami.loadbalancer.server.port=80
    container_name: whoami


networks:
    proxy_aug07:
      driver: bridge
      name: proxy_aug07

