version: '3.7'

services:
  traefik:
    environment:
      - DO_AUTH_TOKEN
    image: "traefik:v2.5"
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik/config:/etc/traefik
    container_name: traefik
    restart: always

  whoami:
    image: "containous/whoami"    
    networks:
      - traefik_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`web.eoastestb.xyz`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=lets-encrypt
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - "traefik.http.routers.whoami.middlewares=traefik2-forward-auth"
    container_name: whoami
#
# use github user id via
# https://github.com/thomseddon/traefik-forward-auth/pull/159
#
  traefik2-forward-auth:
    image: phaustin/traefik-forward-auth:pr159
    environment:
      - DEFAULT_PROVIDER=generic-oauth
      - INSECURE_COOKIE=false # Example assumes no https, do not use in production
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://github.com/login/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://github.com/login/oauth/access_token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://api.github.com/user
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET
      - WHITELIST
      - SECRET
      - USER_ID_PATH=login
    labels:
      - "traefik.http.middlewares.traefik2-forward-auth.forwardauth.address=http://traefik2-forward-auth:4181"
      - "traefik.http.middlewares.traefik2-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik2-forward-auth.loadbalancer.server.port=4181"
      - traefik.enable=true
    networks:
      - traefik_net
    container_name: forward_auth2

networks:
    traefik_net:
      driver: bridge
      name: traefik_net


