version: '3.7'

services:
  traefik:
    environment:
      - DO_AUTH_TOKEN
    image: "traefik:v2.5"
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik/config:/etc/traefik
    container_name: traefik
    restart: always

  whoami:
    image: "containous/whoami"    
    networks:
      - traefik_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`web.eoastestb.xyz`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=lets-encrypt
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - "traefik.http.routers.whoami.middlewares=traefik2-forward-authhost"
    container_name: whoami
#
# use github user id via
# https://github.com/thomseddon/traefik-forward-auth/pull/159
#
  traefik2-forward-authhost:
    # image: phaustin/traefik-forward-auth:pr159
    image: thomseddon/traefik-forward-auth:2
    environment:
      - DEFAULT_PROVIDER=generic-oauth
      - INSECURE_COOKIE=false # Example assumes no https, do not use in production
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://github.com/login/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://github.com/login/oauth/access_token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://api.github.com/user
      - COOKIE_NAME=_github_testhost
      - COOKIE_DOMAIN=eoastest2.xyz
      - AUTH_HOST=auth.eoastest2.xyz
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET
      - WHITELIST
      - SECRET
      - USER_ID_PATH=login
    labels:
      - "traefik.http.middlewares.traefik2-forward-authhost.forwardauth.address=http://traefik2-forward-authhost:4181"
      - "traefik.http.middlewares.traefik2-forward-authhost.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.middlewares.traefik2-forward-authhost.forwardauth.trustForwardHeader=true"
      - "traefik.http.services.traefik2-forward-authhost.loadbalancer.server.port=4181"
      - "traefik.http.routers.traefik2-forward-authhost.tls=true"
      - "traefik.http.routers.traefik2-forward-authhost.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.traefik2-forward-authhost.rule=Host(`auth.eoastest2.xyz`)"
      - "traefik.enable=true"
    networks:
      - traefik_net
    # container_name: forward_authhost

networks:
    traefik_net:
      driver: bridge
      name: traefik_net


