version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy_aug07
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik/config:/etc/traefik
    labels:
      - traefik.enable=true #___ set traefik dashboard + API. The API is available at: mydomain.club/api/http/routers
      - "traefik.http.routers.traefik.rule=Host(`dashboard.eoas.ubc.ca`) && (PathPrefix(`/traefik`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik.service=api@internal" #___ set TLS (https)
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=lets-encrypt" #___ use these middlewares
      - "traefik.http.routers.traefik.middlewares=traefik-strip,dashboardAuth@file" #___ specific middleware for traefik (it enables the dashboard at mydomain.com/traefik)
      - "traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik"
    container_name: traefik
    restart: always

  whoami:
    image: "containous/whoami"
    networks:
      - proxy_aug07
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`dashboard.eoas.ubc.ca`) && PathPrefix(`/try1`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.services.whoami.loadbalancer.server.port=80
    container_name: whoami


networks:
    proxy_aug07:
      driver: bridge
      name: proxy_aug07

