http:
  middlewares:
    dashboard-strip-slash:
        redirectRegex:
          regex: (^.*\/dashboard$)
          replacement: "${1}/"
          permanent: false
    strip-prefix-start:
      redirectregex:
        regex:
          - "^(https?://[^/]+/[a-z0-9_]+)$"
        replacement:
          - "${1}/"
        permanent:
          - true
    strip-prefix-end:
      stripprefixregex:
        regex:
          - "/[a-z0-9_]+"
    dashboardAuth:
      basicAuth:
        users:
          - "eoas:$2y$05$2N25nFVO13/Xxv4JUetyou5eo2xnrZ5rUHXJF0/P59gwZUGgZUdrC"
# https://community.traefik.io/t/middleware-to-add-the-if-needed/1895/19
    cmip6Auth:
      basicAuth:
        users:
          - "cmip6:$2y$05$2N25nFVO13/Xxv4JUetyou5eo2xnrZ5rUHXJF0/P59gwZUGgZUdrC"
    a301Auth:
      basicAuth:
        users:
          - "a301:$2y$05$2N25nFVO13/Xxv4JUetyou5eo2xnrZ5rUHXJF0/P59gwZUGgZUdrC"
    a448Auth:
      basicAuth:
        users:
          - "a448:$2y$05$2N25nFVO13/Xxv4JUetyou5eo2xnrZ5rUHXJF0/P59gwZUGgZUdrC"
    e211Auth:
      basicAuth:
        users:
          - "e211:$2y$05$2N25nFVO13/Xxv4JUetyou5eo2xnrZ5rUHXJF0/P59gwZUGgZUdrC"
