all:
  children:
    local:
    eoas:
local:
  hosts:
    127.0.0.1:
  vars:
    ansible_connection: local
eoas:
  hosts:
    n7:
      ansible_host: node07.eos.ubc.ca
      ansible_ssh_private_key_file: ~/.ssh/tlef_key1
      remote_user: root
    n8:
      ansible_host: node08.eoas.ubc.ca
      ansible_ssh_private_key_file: ~/.ssh/tlef_key1
      remote_user: root

